create table
  public.chats (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    chat_id text not null,
    constraint chats_pkey primary key (id, chat_id),
    constraint chats_chatId_key unique (chat_id)
  ) tablespace pg_default;

  create table
  public.messages (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    status text null default 'send'::text,
    content text null,
    sender_id text null,
    recipient_id text null,
    chat_id text null,
    reply_to text null,
    message_id text not null,
    attachments jsonb[] null,
    duplicate boolean null default false,
    constraint messages_pkey primary key (id, message_id),
    constraint messages_messageId_key unique (message_id)
  ) tablespace pg_default;

  create table
  public.profiles (
    id uuid not null default auth.uid (),
    created_at timestamp with time zone not null default now(),
    username text null,
    status text null default 'Offline'::text,
    profile_pic text null,
    email text null,
    constraint users_pkey primary key (id),
    constraint users_id_key unique (id)
  ) tablespace pg_default;